# Generated by Django 5.0.6 on 2024-10-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'blog_entries',
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('blog_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogentry')),
            ],
        ),
    ]
