# Generated by Django 5.0.6 on 2024-08-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='src',
            field=models.CharField(default='gdffg', max_length=200),
            preserve_default=False,
        ),
    ]
