# Generated by Django 5.0.6 on 2024-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='src_donation',
            field=models.CharField(default='bebra', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='src_video',
            field=models.CharField(default='bimba', max_length=200),
            preserve_default=False,
        ),
    ]
