# Generated by Django 5.0.6 on 2024-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0003_entry_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='src',
            new_name='src_donation',
        ),
        migrations.AddField(
            model_name='entry',
            name='src_video',
            field=models.CharField(default='sfsdfsdf', max_length=200),
            preserve_default=False,
        ),
    ]
