# Generated by Django 5.0.6 on 2024-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0004_rename_src_entry_src_donation_entry_src_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
