# Generated by Django 5.0.6 on 2024-09-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_app', '0003_entry_src_donation_entry_src_video'),
        ('translation_app', '0005_entry_image'),
    ]

    operations = [
    ]
